apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: mysql
        image: mysql:5.7

        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: restaurant

        ports:
        - containerPort: 3306

        volumeMounts:
        - name: initdb
          mountPath: /docker-entrypoint-initdb.d

      volumes:
      - name: initdb
        configMap:
          name: mysql-init
